all: vector-in
	#skipping: conversion conversion-switch squares char-loop char-loop-for vector

conversion:
	g++ -Wall conversion.cpp -o conversion -std=c++14

conversion-switch:
	g++ -Wall conversion-switch.cpp -o conversion-switch -std=c++14

squares:
	g++ -Wall squares.cpp -o squares -std=c++14

char-loop:
	g++ -Wall char-loop.cpp -o char-loop -std=c++14

char-loop-for:
	g++ -Wall char-loop-for.cpp -o char-loop-for -std=c++14

vector:
	g++ -Wall vector.cpp -o vector -std=c++14

vector-in:
	g++ -Wall vector-in.cpp -o vector-in -std=c++14

clean:
	rm -f conversion conversion-switch squares char-loop char-loop-for vector vector-in
